name: FastAPI CI/CD to K3s (GitHub Actions kubectl)

on:
  push:
    branches: ["main"]

jobs:

# ================= CI =================
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest


# ================= CD =================
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code (IMPORTANT FIX)
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
    - name: Debug kubeconfig
      run: |
        grep server kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl config view
        - name: Verify k8s folder exists
          run: |
            ls -la
            ls -la k8s/

    - name: Test cluster connectivity
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=$PWD/kubeconfig

        kubectl apply -f k8s/

        kubectl rollout restart deployment fastapi-app

        kubectl rollout status deployment fastapi-app

        kubectl get pods
        kubectl get svc