name: FastAPI CI/CD to K3s on EC2

on:
  push:
    branches: ["main"]

jobs:

# ===================== CI: Build & Push =====================
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest


# ===================== CD: Deploy to K3s =====================
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Deploy to EC2 K3s Cluster
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |

          echo "==================================="
          echo "Starting Kubernetes Deployment"
          echo "==================================="

          # Set kubeconfig (IMPORTANT FIX)
          export KUBECONFIG=$HOME/.kube/config

          echo "Checking cluster..."
          kubectl get nodes

          echo "Applying Kubernetes manifests..."
          kubectl apply -f k8s/

          echo "Restarting deployment to pull latest image..."
          kubectl rollout restart deployment fastapi-app

          echo "Waiting for rollout..."
          kubectl rollout status deployment fastapi-app

          echo "Pods:"
          kubectl get pods

          echo "Services:"
          kubectl get svc

          echo "Deployment Completed Successfully 🚀"